apiVersion: v1
kind: Service
metadata:
  name: gitops-sample-gateway-active
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 10000
      nodePort: 30001
  selector:
    app: gitops-sample-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gitops-sample-gateway-preview
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 10000
      nodePort: 30002
  selector:
    app: gitops-sample-gateway
